from typing import Dict, Any

def generate_institutional_report_html(data: Dict[str, Any]) -> str:
    """
    Renders an executive institutional wealth strategy document formatted for PDF export and printing.
    """
    capital = data.get("capital", 500000)
    risk = data.get("risk_profile", "medium").upper()
    ret = data.get("projected_return_estimate", "10.8% p.a.")
    metrics = data.get("metrics", {})
    allocations = data.get("allocation", [])
    
    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>FinBot AI Institutional Wealth Report</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; line-height: 1.5; padding: 2rem; background: #ffffff; }}
        .header {{ display: flex; justify-content: space-between; border-bottom: 2px solid #0f172a; padding-bottom: 1rem; margin-bottom: 2rem; }}
        .title {{ font-size: 20pt; font-weight: bold; color: #0f172a; letter-spacing: -0.5px; }}
        .subtitle {{ font-size: 10pt; color: #64748b; font-family: monospace; margin-top: 4px; }}
        .badge {{ background: #0f172a; color: #ffffff; padding: 6px 12px; font-weight: bold; font-family: monospace; font-size: 9pt; }}
        .metrics-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; margin-bottom: 2rem; }}
        .metric-card {{ background: #f8fafc; border: 1px solid #e2e8f0; padding: 1rem; border-radius: 4px; }}
        .m-title {{ font-size: 8pt; text-transform: uppercase; color: #64748b; font-weight: bold; font-family: monospace; }}
        .m-val {{ font-size: 14pt; font-weight: bold; color: #0f172a; margin-top: 4px; font-family: monospace; }}
        table {{ width: 100%; border-collapse: collapse; margin-bottom: 2rem; font-size: 10pt; }}
        th {{ background: #0f172a; color: #ffffff; text-align: left; padding: 10px; font-family: monospace; text-transform: uppercase; font-size: 9pt; }}
        td {{ border-bottom: 1px solid #e2e8f0; padding: 10px; }}
        .disclaimer {{ background: #f1f5f9; border-left: 4px solid #0f172a; padding: 1rem; font-size: 8.5pt; color: #475569; margin-top: 3rem; }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="title">FINBOT AI WEALTH DESK</div>
            <div class="subtitle">INSTITUTIONAL ASSET ALLOCATION &amp; RISK REPORT</div>
        </div>
        <div>
            <span class="badge">RISK TARGET: {risk}</span>
        </div>
    </div>

    <div class="metrics-grid">
        <div class="metric-card">
            <div class="m-title">Total Capital</div>
            <div class="m-val">₹{capital:,}</div>
        </div>
        <div class="metric-card">
            <div class="m-title">Expected Yield</div>
            <div class="m-val">{ret}</div>
        </div>
        <div class="metric-card">
            <div class="m-title">Sharpe Ratio</div>
            <div class="m-val">{metrics.get('sharpe_ratio', 1.52)}</div>
        </div>
        <div class="metric-card">
            <div class="m-title">Annual Volatility</div>
            <div class="m-val">{metrics.get('annual_volatility_pct', 9.4)}%</div>
        </div>
    </div>

    <h3 style="font-family: monospace; font-size: 11pt; border-bottom: 1px solid #cbd5e1; padding-bottom: 6px;">RECOMMENDED ASSET CLASS ALLOCATION</h3>
    <table>
        <thead>
            <tr>
                <th>Asset Class</th>
                <th>Target Weight</th>
                <th>Capital Outlay</th>
                <th>Top Instrument Recommendation</th>
            </tr>
        </thead>
        <tbody>"""

    for item in allocations:
        name = item.get("asset_class", item.get("type", "Asset"))
        pct = item.get("percentage", 0)
        pct_val = pct * 100 if pct <= 1.0 else pct
        amt = item.get("amount", 0)
        recs = item.get("recommendations", [])
        rec_name = recs[0].get("name") if recs else "Index Instrument"
        html += f"""
            <tr>
                <td style="font-weight: bold;">{name}</td>
                <td style="color: #0ea5e9; font-family: monospace; font-weight: bold;">{pct_val:.1f}%</td>
                <td style="font-family: monospace;">₹{amt:,}</td>
                <td>{rec_name}</td>
            </tr>"""

    html += f"""
        </tbody>
    </table>

    <div class="disclaimer">
        <strong>REGULATORY DISCLAIMER &amp; FIDUCIARY NOTICE:</strong><br>
        This document is generated by FinBot AI Quantitative Advisory Engine for informational and strategic asset allocation purposes. All performance estimates, Sharpe ratios, and Monte Carlo probability models are based on historical statistical correlations and do not guarantee future performance.
    </div>
</body>
</html>"""

    return html
